<?php

namespace App\Tests\Service;

use App\Service\FileUploadService;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use function PHPUnit\Framework\assertFileExists;

class FileUploadServiceTest extends WebTestCase {
    /**
     * @var string
     */
    private string $filename;

    /**
     * @var
     */
    private $uploadedFileFromRequest;

    protected function setUp(): void {
        $projectDir = getcwd();
        copy($projectDir.'/storage/csvfiles/stock.csv', $projectDir.'/storage/test/csvfiles/stock.csv');
        $uploadedFile = new UploadedFile($projectDir.'/storage/test/csvfiles/stock.csv', 'stock.csv');

        $client = static::createClient();
        $client->request('POST', '/', [], [
            'upload_file' => $uploadedFile
        ]);
        $container = $client->getContainer();
        $uploadFileService = $container->get(FileUploadService::class);
        $this->uploadedFileFromRequest = $client->getRequest()->files->get('upload_file');
        $this->filename = $uploadFileService->upload($this->uploadedFileFromRequest);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     */
    public function testUpload() {
        assertFileExists($this->filename);
    }

    public function tearDown(): void {
        parent::tearDown(); // TODO: Change the autogenerated stub
        unlink($this->filename);
    }
}
