<?php

namespace App\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class UploadFileControllerTest extends WebTestCase {
    /**
     * @var KernelBrowser
     */
    private KernelBrowser $client;
    protected function setUp(): void {
        $this->client = static::createClient();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex(): void {
        $this->client->request('GET', '/');

        self::assertResponseIsSuccessful();
    }
}
